In [1]:
import common.generators as gen
import struckpod.walks as wks
import networkx as nx
import kyle_exploration.nonnegcriterion as nneg
import numpy as np

In [2]:
star_dict = gen.starfish_hyperchain(4,2,[5,3])
A = nx.adjacency_matrix(star_dict['graph']).todense()
print('\nNum nodes = ' + str(len(star_dict['graph'])))

obj = wks.starfish_hyperchain_walk_classes(star_dict)
W = obj['uniq_matrix']
representatives = obj['uniq_rows']

nneg.check_nonnegative_criterion(A, W, representatives)


Num nodes = 135

g
[[ 4.59258973]
 [ 4.54593088]
 [ 3.8544811 ]]


     fun: 4.8683263499083651
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([ 0.        ,  0.2640719 ,  0.        ,  0.01166471,  4.59258973])
  status: 0
 success: True
       x: array([ 0.        ,  0.2640719 ,  0.        ,  0.01166471,  4.59258973])

Diagonal entries of our constructed function of this graph:
[[4.592589734861856]
 [4.592589734861856]
 [4.592589734861856]]


In [5]:
star_dict = gen.starfish_hyperchain(7,2,[5,3])
A = nx.adjacency_matrix(star_dict['graph']).todense()
print('\nNum nodes = ' + str(len(star_dict['graph'])))

obj = wks.starfish_hyperchain_walk_classes(star_dict)
W = obj['uniq_matrix']
representatives = obj['uniq_rows']

nneg.check_nonnegative_criterion(A, W, representatives)


Num nodes = 225

g
[[ 8.91783422]
 [ 4.82732637]
 [ 3.86181625]]


     fun: 3.8146478165841762
 message: 'Optimization failed. Unable to find a feasible starting point.'
     nit: 2
  status: 2
 success: False
       x: nan


TypeError: 'float' object is not subscriptable

In [6]:
star_dict = gen.starfish_hyperchain(4,3,[7,5,3])
A = nx.adjacency_matrix(star_dict['graph']).todense()
print('\nNum nodes = ' + str(len(star_dict['graph'])))

obj = wks.starfish_hyperchain_walk_classes(star_dict)
W = obj['uniq_matrix']
representatives = obj['uniq_rows']

nneg.check_nonnegative_criterion(A, W, representatives)


Num nodes = 1365

g
[[ 4.59649562]
 [ 4.57236759]
 [ 4.52046057]
 [ 3.85405843]]


     fun: 12.146702822642256
 message: 'Optimization terminated successfully.'
     nit: 7
   slack: array([  0.00000000e+00,   1.35464748e+00,   2.13501324e-01,
         0.00000000e+00,   0.00000000e+00,   4.02133860e-03,
         1.05745327e+01])
  status: 0
 success: True
       x: array([  0.00000000e+00,   1.35464748e+00,   2.13501324e-01,
         0.00000000e+00,   0.00000000e+00,   4.02133860e-03,
         1.05745327e+01])

Diagonal entries of our constructed function of this graph:
[[10.574532680168854]
 [10.574532680168854]
 [10.574532680168854]
 [10.574532680168856]]


In [7]:
W

matrix([[4.0, 0.0, 28.0, 0.0, 256.0, 0.0],
        [4.0, 0.0, 28.0, 0.0, 243.0, 6.0],
        [4.0, 0.0, 27.0, 4.0, 212.0, 72.0],
        [3.0, 2.0, 16.0, 18.0, 107.0, 148.0]], dtype=object)